import { getDb } from "../sqliteDb";

type SeedRow = {
  Id: string;
  EmployeeId: string;
  EmployeeName: string;
  Email: string | null;
  Manager: string;
  Position: string;
  FunctionName: string | null;
  Department: string | null;
  Grade: string;
  Location: string | null;
  LengthOfService: string | null;
  Age: string | null;
  SeparationDate: string;
  PrimaryReason: string;
  SecondaryReason: string | null;
  TertiaryReason: string | null;
  SingleTriggerEvent: number | null;
  SingleTriggerExplanation: string | null;
  Preventable: number | null;
  PreventableExplanation: string | null;
  Suggestions: string;
  WouldRecommend: number | null;
  AcceptedAnotherJob: number | null;
  NewEmployer: string | null;
  NewJobTitle: string | null;
  NewJobLocation: string | null;
  HowFoundJob: string | null;
  HowLongLooking: string | null;
};

const rows: SeedRow[] = [
  {
    Id: "seed-001",
    EmployeeId: "DHL001",
    EmployeeName: "Amina Bello",
    Email: "amina.bello@dhl.com",
    Manager: "Chinedu Okafor",
    Position: "HR Officer",
    FunctionName: "People Services",
    Department: "HR",
    Grade: "M",
    Location: "Lagos",
    LengthOfService: "3 years",
    Age: "31",
    SeparationDate: "2026-01-15",
    PrimaryReason: "Career growth",
    SecondaryReason: "Better opportunity elsewhere",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 1,
    PreventableExplanation: "Clearer progression pathways may have helped.",
    Suggestions: "Provide clearer internal career growth opportunities.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 1,
    NewEmployer: "TalentBridge Africa",
    NewJobTitle: "Senior HR Executive",
    NewJobLocation: "Lagos",
    HowFoundJob: "LinkedIn",
    HowLongLooking: "2 months",
  },
  {
    Id: "seed-002",
    EmployeeId: "DHL002",
    EmployeeName: "Tunde Adebayo",
    Email: "tunde.adebayo@dhl.com",
    Manager: "Mariam Yusuf",
    Position: "IT Support Analyst",
    FunctionName: "Infrastructure",
    Department: "IT",
    Grade: "L",
    Location: "Lagos",
    LengthOfService: "2 years",
    Age: "29",
    SeparationDate: "2026-02-10",
    PrimaryReason: "Compensation and benefits",
    SecondaryReason: "Career growth",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 1,
    PreventableExplanation: "Pay review and role expansion may have retained the employee.",
    Suggestions: "Review salary competitiveness for technical roles.",
    WouldRecommend: 0,
    AcceptedAnotherJob: 1,
    NewEmployer: "CloudAxis",
    NewJobTitle: "Systems Engineer",
    NewJobLocation: "Lagos",
    HowFoundJob: "Referral",
    HowLongLooking: "1 month",
  },
  {
    Id: "seed-003",
    EmployeeId: "DHL003",
    EmployeeName: "Esther Okon",
    Email: "esther.okon@dhl.com",
    Manager: "Bola Kareem",
    Position: "Customer Service Advisor",
    FunctionName: "Contact Centre",
    Department: "Customer service",
    Grade: "N",
    Location: "Abuja",
    LengthOfService: "1 year 8 months",
    Age: "27",
    SeparationDate: "2026-02-25",
    PrimaryReason: "Manager relationship",
    SecondaryReason: "Work-life balance",
    TertiaryReason: null,
    SingleTriggerEvent: 1,
    SingleTriggerExplanation: "A difficult escalation changed her view of staying.",
    Preventable: 1,
    PreventableExplanation: "Earlier intervention and coaching may have helped.",
    Suggestions: "Improve line manager coaching and conflict handling.",
    WouldRecommend: 0,
    AcceptedAnotherJob: 0,
    NewEmployer: null,
    NewJobTitle: null,
    NewJobLocation: null,
    HowFoundJob: null,
    HowLongLooking: "3 months",
  },
  {
    Id: "seed-004",
    EmployeeId: "DHL004",
    EmployeeName: "Ifeanyi Nwosu",
    Email: "ifeanyi.nwosu@dhl.com",
    Manager: "Grace Nnamdi",
    Position: "Operations Supervisor",
    FunctionName: "Hub Operations",
    Department: "Operations",
    Grade: "M",
    Location: "Lagos",
    LengthOfService: "5 years",
    Age: "38",
    SeparationDate: "2026-03-12",
    PrimaryReason: "Work-life balance",
    SecondaryReason: "Compensation and benefits",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 1,
    PreventableExplanation: "Shift planning improvements may have helped.",
    Suggestions: "Review shift patterns and workload distribution.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 1,
    NewEmployer: "Swift Parcel Network",
    NewJobTitle: "Operations Manager",
    NewJobLocation: "Lagos",
    HowFoundJob: "Recruiter",
    HowLongLooking: "4 months",
  },
  {
    Id: "seed-005",
    EmployeeId: "DHL005",
    EmployeeName: "Fatima Sani",
    Email: "fatima.sani@dhl.com",
    Manager: "Ayo Thomas",
    Position: "Sales Executive",
    FunctionName: "Field Sales",
    Department: "Commercial",
    Grade: "L",
    Location: "Abuja",
    LengthOfService: "2 years 4 months",
    Age: "30",
    SeparationDate: "2026-03-28",
    PrimaryReason: "Better opportunity elsewhere",
    SecondaryReason: "Career growth",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 0,
    PreventableExplanation: "The new role was a significant jump.",
    Suggestions: "Strengthen talent retention for high-performing sales staff.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 1,
    NewEmployer: "PrimeTrade Logistics",
    NewJobTitle: "Key Account Manager",
    NewJobLocation: "Abuja",
    HowFoundJob: "LinkedIn",
    HowLongLooking: "2 months",
  },
  {
    Id: "seed-006",
    EmployeeId: "DHL006",
    EmployeeName: "Ngozi Eze",
    Email: "ngozi.eze@dhl.com",
    Manager: "Peter Adams",
    Position: "Executive Assistant",
    FunctionName: "Executive Office",
    Department: "General management",
    Grade: "M",
    Location: "Lagos",
    LengthOfService: "4 years",
    Age: "35",
    SeparationDate: "2026-04-05",
    PrimaryReason: "Relocation",
    SecondaryReason: "Personal reasons",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 0,
    PreventableExplanation: "Relocation was outside company control.",
    Suggestions: "Consider remote or hybrid support roles where feasible.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 0,
    NewEmployer: null,
    NewJobTitle: null,
    NewJobLocation: null,
    HowFoundJob: null,
    HowLongLooking: null,
  },
  {
    Id: "seed-007",
    EmployeeId: "DHL007",
    EmployeeName: "Samuel Ojo",
    Email: "samuel.ojo@dhl.com",
    Manager: "Linda Obi",
    Position: "Finance Analyst",
    FunctionName: "Financial Planning",
    Department: "Finance",
    Grade: "L",
    Location: "Lagos",
    LengthOfService: "3 years 6 months",
    Age: "33",
    SeparationDate: "2026-04-18",
    PrimaryReason: "Compensation and benefits",
    SecondaryReason: "Better opportunity elsewhere",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 1,
    PreventableExplanation: "Pay benchmarking may have improved retention.",
    Suggestions: "Benchmark finance salaries more frequently.",
    WouldRecommend: 0,
    AcceptedAnotherJob: 1,
    NewEmployer: "Vertex Capital",
    NewJobTitle: "Senior Financial Analyst",
    NewJobLocation: "Lagos",
    HowFoundJob: "Referral",
    HowLongLooking: "1 month",
  },
  {
    Id: "seed-008",
    EmployeeId: "DHL008",
    EmployeeName: "Blessing Iro",
    Email: "blessing.iro@dhl.com",
    Manager: "Chinedu Okafor",
    Position: "HR Business Partner",
    FunctionName: "HR Business Partnering",
    Department: "HR",
    Grade: "M",
    Location: "Port Harcourt",
    LengthOfService: "6 years",
    Age: "37",
    SeparationDate: "2026-04-26",
    PrimaryReason: "Personal reasons",
    SecondaryReason: null,
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 0,
    PreventableExplanation: "Personal circumstances drove the decision.",
    Suggestions: "Continue strengthening employee wellbeing programmes.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 0,
    NewEmployer: null,
    NewJobTitle: null,
    NewJobLocation: null,
    HowFoundJob: null,
    HowLongLooking: null,
  },
  {
    Id: "seed-009",
    EmployeeId: "DHL009",
    EmployeeName: "Kelvin James",
    Email: "kelvin.james@dhl.com",
    Manager: "Mariam Yusuf",
    Position: "Application Support Specialist",
    FunctionName: "Business Applications",
    Department: "IT",
    Grade: "M",
    Location: "Lagos",
    LengthOfService: "4 years 2 months",
    Age: "34",
    SeparationDate: "2026-05-02",
    PrimaryReason: "Career growth",
    SecondaryReason: "Better opportunity elsewhere",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 1,
    PreventableExplanation: "More visible technical progression could help.",
    Suggestions: "Create clearer specialist career tracks in IT.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 1,
    NewEmployer: "Nexa Systems",
    NewJobTitle: "Solutions Lead",
    NewJobLocation: "Lagos",
    HowFoundJob: "LinkedIn",
    HowLongLooking: "3 months",
  },
  {
    Id: "seed-010",
    EmployeeId: "DHL010",
    EmployeeName: "Ruth Danjuma",
    Email: "ruth.danjuma@dhl.com",
    Manager: "Bola Kareem",
    Position: "Customer Experience Officer",
    FunctionName: "Customer Experience",
    Department: "Customer service",
    Grade: "N",
    Location: "Kano",
    LengthOfService: "2 years",
    Age: "28",
    SeparationDate: "2026-05-10",
    PrimaryReason: "Organisational culture",
    SecondaryReason: "Manager relationship",
    TertiaryReason: null,
    SingleTriggerEvent: 1,
    SingleTriggerExplanation: "Repeated tension within the team affected engagement.",
    Preventable: 1,
    PreventableExplanation: "Team climate intervention may have helped.",
    Suggestions: "Invest more in manager capability and team culture.",
    WouldRecommend: 0,
    AcceptedAnotherJob: 0,
    NewEmployer: null,
    NewJobTitle: null,
    NewJobLocation: null,
    HowFoundJob: null,
    HowLongLooking: "2 months",
  },
  {
    Id: "seed-011",
    EmployeeId: "DHL011",
    EmployeeName: "Daniel Umeh",
    Email: "daniel.umeh@dhl.com",
    Manager: "Grace Nnamdi",
    Position: "Warehouse Coordinator",
    FunctionName: "Warehouse Operations",
    Department: "Operations",
    Grade: "N",
    Location: "Lagos",
    LengthOfService: "1 year 10 months",
    Age: "26",
    SeparationDate: "2026-05-14",
    PrimaryReason: "Compensation and benefits",
    SecondaryReason: "Work-life balance",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 1,
    PreventableExplanation: "Better total reward structure may have improved retention.",
    Suggestions: "Review benefits for operational front-line staff.",
    WouldRecommend: 0,
    AcceptedAnotherJob: 1,
    NewEmployer: "Metro Fulfilment",
    NewJobTitle: "Warehouse Lead",
    NewJobLocation: "Lagos",
    HowFoundJob: "Referral",
    HowLongLooking: "1 month",
  },
  {
    Id: "seed-012",
    EmployeeId: "DHL012",
    EmployeeName: "Halima Garba",
    Email: "halima.garba@dhl.com",
    Manager: "Ayo Thomas",
    Position: "Account Manager",
    FunctionName: "Key Accounts",
    Department: "Commercial",
    Grade: "M",
    Location: "Abuja",
    LengthOfService: "5 years 3 months",
    Age: "36",
    SeparationDate: "2026-05-18",
    PrimaryReason: "Career growth",
    SecondaryReason: null,
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 1,
    PreventableExplanation: "Succession planning may have helped.",
    Suggestions: "Improve internal mobility visibility for strong performers.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 1,
    NewEmployer: "WestBridge Distribution",
    NewJobTitle: "Commercial Manager",
    NewJobLocation: "Abuja",
    HowFoundJob: "Recruiter",
    HowLongLooking: "2 months",
  },
  {
    Id: "seed-013",
    EmployeeId: "DHL013",
    EmployeeName: "Patience Effiong",
    Email: "patience.effiong@dhl.com",
    Manager: "Peter Adams",
    Position: "Strategy Analyst",
    FunctionName: "Corporate Strategy",
    Department: "General management",
    Grade: "M",
    Location: "Lagos",
    LengthOfService: "3 years",
    Age: "32",
    SeparationDate: "2026-05-22",
    PrimaryReason: "Better opportunity elsewhere",
    SecondaryReason: "Career growth",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 0,
    PreventableExplanation: "Opportunity was significantly broader in scope.",
    Suggestions: "Continue to retain top talent with visible stretch assignments.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 1,
    NewEmployer: "BluePeak Advisory",
    NewJobTitle: "Senior Strategy Consultant",
    NewJobLocation: "Lagos",
    HowFoundJob: "LinkedIn",
    HowLongLooking: "2 months",
  },
  {
    Id: "seed-014",
    EmployeeId: "DHL014",
    EmployeeName: "Michael Akin",
    Email: "michael.akin@dhl.com",
    Manager: "Linda Obi",
    Position: "Accounts Officer",
    FunctionName: "Accounts Payable",
    Department: "Finance",
    Grade: "N",
    Location: "Ibadan",
    LengthOfService: "2 years 7 months",
    Age: "30",
    SeparationDate: "2026-05-25",
    PrimaryReason: "Relocation",
    SecondaryReason: null,
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 0,
    PreventableExplanation: "Move was for family reasons.",
    Suggestions: "Maintain good offboarding support for relocating staff.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 0,
    NewEmployer: null,
    NewJobTitle: null,
    NewJobLocation: null,
    HowFoundJob: null,
    HowLongLooking: null,
  },
  {
    Id: "seed-015",
    EmployeeId: "DHL015",
    EmployeeName: "Joy Chukwu",
    Email: "joy.chukwu@dhl.com",
    Manager: "Grace Nnamdi",
    Position: "Operations Analyst",
    FunctionName: "Network Operations",
    Department: "Operations",
    Grade: "L",
    Location: "Lagos",
    LengthOfService: "3 years 4 months",
    Age: "31",
    SeparationDate: "2026-05-30",
    PrimaryReason: "Career growth",
    SecondaryReason: "Compensation and benefits",
    TertiaryReason: null,
    SingleTriggerEvent: 0,
    SingleTriggerExplanation: null,
    Preventable: 1,
    PreventableExplanation: "A stronger development plan might have helped.",
    Suggestions: "Strengthen development planning for mid-career employees.",
    WouldRecommend: 1,
    AcceptedAnotherJob: 1,
    NewEmployer: "Axis Logistics",
    NewJobTitle: "Senior Operations Analyst",
    NewJobLocation: "Lagos",
    HowFoundJob: "LinkedIn",
    HowLongLooking: "3 months",
  },
];

async function main() {
  const db = await getDb();

  await db.exec("DELETE FROM ExitInterviews;");

  const insertSql = `
    INSERT INTO ExitInterviews (
      Id, EmployeeId, EmployeeName, Email, Manager, Position,
      FunctionName, Department, Grade, Location,
      LengthOfService, Age, SeparationDate,
      PrimaryReason, SecondaryReason, TertiaryReason,
      SingleTriggerEvent, SingleTriggerExplanation,
      Preventable, PreventableExplanation,
      Suggestions, WouldRecommend,
      AcceptedAnotherJob, NewEmployer, NewJobTitle, NewJobLocation,
      HowFoundJob, HowLongLooking
    )
    VALUES (
      ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?,
      ?, ?, ?,
      ?, ?, ?,
      ?, ?,
      ?, ?,
      ?, ?,
      ?, ?, ?, ?,
      ?, ?
    )
  `;

  for (const row of rows) {
    await db.run(insertSql, [
      row.Id,
      row.EmployeeId,
      row.EmployeeName,
      row.Email,
      row.Manager,
      row.Position,
      row.FunctionName,
      row.Department,
      row.Grade,
      row.Location,
      row.LengthOfService,
      row.Age,
      row.SeparationDate,
      row.PrimaryReason,
      row.SecondaryReason,
      row.TertiaryReason,
      row.SingleTriggerEvent,
      row.SingleTriggerExplanation,
      row.Preventable,
      row.PreventableExplanation,
      row.Suggestions,
      row.WouldRecommend,
      row.AcceptedAnotherJob,
      row.NewEmployer,
      row.NewJobTitle,
      row.NewJobLocation,
      row.HowFoundJob,
      row.HowLongLooking,
    ]);
  }

  console.log(`Reset complete. Inserted ${rows.length} dummy exit interview records.`);
}

main().catch((err) => {
  console.error("Failed to reset and seed database", err);
  process.exit(1);
});
